# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Chekc path
        run: echo $GITHUB_WORKSPACE

      - name: list path
        run: cd $GITHUB_WORKSPACE/pgdba-cli && go mod download

      - name: Build
        run:  make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pgdba-cli
          path: pgdba-cli
